### ISSUE TITLE
ECR repo not found.

### ISSUE THREAD

**Issue by shivani-hotstar** [tmobile/pacbot#300] opened 2019-09-16 07:22 UTC
Hi,
While setting up pacbot on centos 7 AMI i am facing below issue even though the ECR repo is already created in my aws account.

Running Command: /opt/pacbot/installer/manager.py install
Traceback (most recent call last):
  File "/opt/pacbot/installer/core/kernel.py", line 182, in run
    self.execute(command_class_instance)
  File "/opt/pacbot/installer/core/kernel.py", line 24, in execute
    self.execute_command(command_class_instance)
  File "/opt/pacbot/installer/core/kernel.py", line 36, in execute_command
    command_class_instance.execute(self.provider)
  File "/opt/pacbot/installer/core/commands/install.py", line 48, in execute
    self.dry_run
  File "/opt/pacbot/installer/core/providers/aws/install.py", line 71, in execute
    raise self.exception
  File "/opt/pacbot/installer/core/providers/aws/install.py", line 104, in create_resources
    self.terraform_apply(resources, terraform_with_targets, dry_run)
  File "/opt/pacbot/installer/core/providers/aws/install.py", line 185, in terraform_apply
    py_terraform.terraform_apply(apply_resources)
  File "/opt/pacbot/installer/core/terraform/__init__.py", line 103, in terraform_apply
    raise Exception(response[2])
Exception:
Error: Error applying plan:

2 error(s) occurred:

* null_resource.batch_ecr_RuleEngineDockerImageBuild: Error running command '/opt/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py': exit status 1. Output: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.24/images/xyz.ecr.ap-south-1.amazonaws.com/pacbot-rule-engine?force=True&noprune=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py", line 80, in <module>
    build_and_push_docker_image(provider_json_file, ecr_repo, docker_file, docker_file_dir, log_file)
  File "/opt/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py", line 35, in build_and_push_docker_image
    delete_docker_images_from_local(os.path.join(docker_file_dir, docker_file))
  File "/opt/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py", line 51, in delete_docker_images_from_local
    docker_client.remove_image(ecr_repo, force=True)
  File "/usr/local/lib/python3.6/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/api/image.py", line 223, in remove_image
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("b'{"message":"No such image: xyz.ecr.ap-south-1.amazonaws.com/pacbot-rule-engine:latest"}'")

* null_resource.pacbot_app_ecr_APIDockerImageBuild: Error running command '/opt/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py': exit status 1. Output: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.24/images/xyz.ecr.ap-south-1.amazonaws.com/pacbot-microservices?force=True&noprune=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py", line 80, in <module>
    build_and_push_docker_image(provider_json_file, ecr_repo, docker_file, docker_file_dir, log_file)
  File "/opt/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py", line 35, in build_and_push_docker_image
    delete_docker_images_from_local(os.path.join(docker_file_dir, docker_file))
  File "/opt/pacbot/installer/data/terraform/scripts_and_files/scripts/create_docker_image_and_push_to_ecr.py", line 51, in delete_docker_images_from_local
    docker_client.remove_image(ecr_repo, force=True)
  File "/usr/local/lib/python3.6/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/api/image.py", line 223, in remove_image
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("b'{"message":"No such image: xyz.ecr.ap-south-1.amazonaws.com/pacbot-microservices:latest"}'")

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-463

**Comment by sajeer-nooh** [comment] 2019-09-16 07:57
Ideally, this should not happen, but could you please confirm whether this error occurred during the first time or have you tried more than one time?
If so, could you please destroy and re-install again. If the error still persists we recommend to use Amazon Linux machine for installation.

**Comment by shivani-hotstar** [comment] 2019-09-16 09:20
I have tried two times at first attempt i was getting below error:-
aws_cloudwatch_event_rule.lambda_rule_engine_function_RuleEngineEventRules.79: Updating CloudWatch Event Rule failed: LimitExceededException: The requested resource exceeds the maximum number allowed.
This was bec of my acc limits so after solving this i made one change also .

cat rule_engine_cloudwatch_rules.json 
[
  {
    "ruleId": "PacMan_EC2WithPublicAccessSSHPort22_version-2_EC2WithPublicAccessForConfiguredPort22_ec2",
    "ruleUUID": "aws_ec2_should_not_be_publicly_accessible_on_port22",
    "policyId": "PacMan_EC2WithPublicAccessSSHPort22_version-2",
    "ruleName": "EC2WithPublicAccessForConfiguredPort22",
    "targetType": "ec2",
    "assetGroup": "aws",
    "alexaKeyword": "EC2WithPublicAccessForConfiguredPort22",
    "ruleParams": "{\"params\":[{\"encrypt\":false,\"value\":\"igw\",\"key\":\"internetGateWay\"},{\"encrypt\":false,\"value\":\"22\",\"key\":\"portToCheck\"},{\"encrypt\":false,\"value\":\"check-for-ec2-with-public-access-for-configured-port\",\"key\":\"ruleKey\"},{\"encrypt\":false,\"value\":\"security\",\"key\":\"ruleCategory\"},{\"encrypt\":false,\"value\":\"critical\",\"key\":\"severity\"},{\"encrypt\":false,\"value\":\"0.0.0.0/0\",\"key\":\"cidrIp\"},{\"key\":\"esEc2SgURL\",\"value\":\"/aws/ec2_secgroups/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esRoutetableAssociationsURL\",\"value\":\"/aws_routetable/routetable_associations/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esRoutetableRoutesURL\",\"value\":\"/aws_routetable/routetable_routes/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esRoutetableURL\",\"value\":\"/aws_routetable/routetable/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esSgRulesUrl\",\"value\":\"/aws_sg/sg_rules/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esSubnetURL\",\"value\":\"/aws_subnet/_search\",\"isValueNew\":true,\"encrypt\":false}],\"environmentVariables\":[],\"ruleId\":\"PacMan_EC2WithPublicAccessSSHPort22_version-2_EC2WithPublicAccessForConfiguredPort22_ec2\",\"autofix\":false,\"alexaKeyword\":\"EC2WithPublicAccessForConfiguredPort22\",\"ruleRestUrl\":\"\",\"targetType\":\"ec2\",\"pac_ds\":\"aws\",\"policyId\":\"PacMan_EC2WithPublicAccessSSHPort22_version-2\",\"assetGroup\":\"aws\",\"ruleUUID\":\"aws_ec2_should_not_be_publicly_accessible_on_port22\",\"ruleType\":\"ManageRule\"}",
    "ruleFrequency": "0 * * * ? *",
    "ruleExecutable": "",
    "ruleRestUrl": "",
    "ruleType": "ManageRule",
    "ruleArn": "arn:aws:events:us-east-1:***REMOVED***:rule/aws_ec2_should_not_be_publicly_accessible_on_port22",
    "status": "ENABLED",
    "userId": "ASGC",
    "displayName": "EC2 instances should not be publicly accessible on SSH port 22",
    "createdDate": "2017-08-23",
    "modifiedDate": "2018-11-09",
    "severity": null,
    "category": null
  },
  {
    "ruleId": "PacMan_EC2WithPublicIPAccess_version-1_Ec2WithPublicAccess_ec2",
    "ruleUUID": "aws_EC2_should_not_be_publicly_accessible_with_any_port",
    "policyId": "PacMan_EC2WithPublicIPAccess_version-1",
    "ruleName": "Ec2WithPublicAccess",
    "targetType": "ec2",
    "assetGroup": "aws",
    "alexaKeyword": "Ec2WithPublicAccess",
    "ruleParams": "{\"params\":[{\"encrypt\":\"false\",\"value\":\"igw\",\"key\":\"internetGateWay\"},{\"encrypt\":\"false\",\"value\":\"check-for-ec2-public-access\",\"key\":\"ruleKey\"},{\"encrypt\":false,\"value\":\"critical\",\"key\":\"severity\"},{\"encrypt\":false,\"value\":\"security\",\"key\":\"ruleCategory\"},{\"encrypt\":false,\"value\":\"0.0.0.0/0\",\"key\":\"cidrIp\"},{\"key\":\"esEc2SgURL\",\"value\":\"/aws/ec2_secgroups/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esRoutetableAssociationsURL\",\"value\":\"/aws_routetable/routetable_associations/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esRoutetableRoutesURL\",\"value\":\"/aws_routetable/routetable_routes/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esRoutetableURL\",\"value\":\"/aws_routetable/routetable/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esSgRulesUrl\",\"value\":\"/aws_sg/sg_rules/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"esSubnetURL\",\"value\":\"/aws_subnet/_search\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"cidripv6\",\"value\":\"::/0\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"defaultCidrIp\",\"value\":\"\",\"isValueNew\":true,\"encrypt\":false},{\"key\":\"fixKey\",\"value\":\"ec2-global-access-fix\",\"isValueNew\":true,\"encrypt\":false}],\"environmentVariables\":[{\"encrypt\":false,\"value\":\"123\",\"key\":\"abc\"}],\"ruleId\":\"PacMan_EC2WithPublicIPAccess_version-1_Ec2WithPublicAccess_ec2\",\"autofix\":false,\"alexaKeyword\":\"Ec2WithPublicAccess\",\"ruleRestUrl\":\"\",\"targetType\":\"ec2\",\"pac_ds\":\"aws\",\"policyId\":\"PacMan_EC2WithPublicIPAccess_version-1\",\"assetGroup\":\"aws\",\"ruleUUID\":\"aws_EC2_should_not_be_publicly_accessible_with_any_port\",\"ruleType\":\"ManageRule\"}",
    "ruleFrequency": "0 * * * ? *",
    "ruleExecutable": "",
    "ruleRestUrl": "",
    "ruleType": "ManageRule",
    "ruleArn": "arn:aws:events:us-east-1:***REMOVED***:rule/aws_EC2_should_not_be_publicly_accessible_with_any_port",
    "status": "ENABLED",
    "userId": "ASGC",
    "displayName": "EC2 instances should not have any publicly accessible ports",
    "createdDate": "2017-08-18",
    "modifiedDate": "2018-12-10",
    "severity": null,
    "category": null
  }
]

Removed other rules and start setting up with these two rules only.

Also,
destroy and re-install didn't work here .

The AMI i am using --> centos-7-pke-201907251446 (ami-002d6833390304363)

**Comment by sajeer-nooh** [comment] 2019-09-16 09:57
1. The cloudwatch rule error is due to the limit. By default AWS support only 100 rules but PacBot alone need 105 rules. It would be better if you contact AWS support and increase the limit as PacBot need all the rules for working properly. Without them, no data will be fetched.
2. I would suggest destroy everything, increase the limit and confirm it and then install.
3. If possible try to setup from Amazon Linux AMI with at least t2.medium type machine

**Comment by shivani-hotstar** [comment] 2019-09-18 06:29
I am using centos-7-pke-201907251446 (ami-002d6833390304363) and did my setup on t2.medium .
Can you confirm that i am using only rule_engine_cloudwatch_rules.json only two rules under this file . Is this is creating any issue.
because tried 3 times destroy and reinstalling didn't work.

**Comment by sajeer-nooh** [comment] 2019-09-18 06:32
rule_engine_cloudwatch_rules.json with 2 rules will not make a problem to the installation.

**Comment by sajeer-nooh** [comment] 2019-09-18 06:44
This error seems to be building docker image at the installer machine. Somehow it is failing.  Please check log/debug.log to identify what exactly happened during image build.

This can be confirmed manually by building the image from the docker file in, https://github.com/tmobile/pacbot/tree/master/installer/resources/pacbot_app/files/api_docker.

You can go to /pacbot/installer/data/terraform/scripts_and_files/api_docker, and manully try buulding the image.

**Comment by santhoshigorle** [comment] 2019-10-04 21:40
closing

**Closed by santhoshigorle** 2019-10-04 21:41 UTC
Labels: help wanted

**Comment by msrsooraj** [comment] 2020-09-21 11:20
I ran into this issue because the virtual machine ran out of disk space.

**Comment by bestras023** [comment] 2021-06-09 17:33
Hi, @sajeer-nooh I have the same issue as @shivani-hotstar . I'm using amazon linux 2.
I tried to destroy and re-install. But the same issue happens.
Please help me.

**Comment by SuharshTyagii** [comment] 2022-01-18 11:24
Facing the same issue on amazon linux 2. Can you please help @sajeer-nooh ?
